/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBrowserScopeProvider extends DelegatingScopeProvider {
}
