/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.browser.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.browser.BrowserPackage;
import org.xtext.example.browser.WebDriverVarReference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Web Driver Var Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WebDriverVarReferenceImpl extends MinimalEObjectImpl.Container implements WebDriverVarReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WebDriverVarReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserPackage.Literals.WEB_DRIVER_VAR_REFERENCE;
  }

} //WebDriverVarReferenceImpl
