/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ui.AbstractBrowserUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BrowserUiModule extends AbstractBrowserUiModule {
  public BrowserUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
