/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Find Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.browser.FindProperty#getRef <em>Ref</em>}</li>
 *   <li>{@link org.xtext.example.browser.FindProperty#getVal <em>Val</em>}</li>
 *   <li>{@link org.xtext.example.browser.FindProperty#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.browser.FindProperty#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.browser.BrowserPackage#getFindProperty()
 * @model
 * @generated
 */
public interface FindProperty extends Lines
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(VarReference)
   * @see org.xtext.example.browser.BrowserPackage#getFindProperty_Ref()
   * @model containment="true"
   * @generated
   */
  VarReference getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.browser.FindProperty#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(VarReference value);

  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(WebDriverVarReference)
   * @see org.xtext.example.browser.BrowserPackage#getFindProperty_Val()
   * @model containment="true"
   * @generated
   */
  WebDriverVarReference getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.browser.FindProperty#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(WebDriverVarReference value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.browser.BrowserPackage#getFindProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.browser.FindProperty#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' attribute.
   * @see #setParam(String)
   * @see org.xtext.example.browser.BrowserPackage#getFindProperty_Param()
   * @model
   * @generated
   */
  String getParam();

  /**
   * Sets the value of the '{@link org.xtext.example.browser.FindProperty#getParam <em>Param</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' attribute.
   * @see #getParam()
   * @generated
   */
  void setParam(String value);

} // FindProperty
