/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.browser.Image#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.browser.BrowserPackage#getImage()
 * @model
 * @generated
 */
public interface Image extends WebElementType
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(WebElementVarReference)
   * @see org.xtext.example.browser.BrowserPackage#getImage_Value()
   * @model containment="true"
   * @generated
   */
  WebElementVarReference getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.browser.Image#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(WebElementVarReference value);

} // Image
