/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.browser.BrowserPackage;
import org.xtext.example.mydsl.browser.FunctionCall;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FunctionCallImpl extends LinesImpl implements FunctionCall
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionCallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserPackage.Literals.FUNCTION_CALL;
  }

} //FunctionCallImpl
