/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.browser.BrowserPackage;
import org.xtext.example.mydsl.browser.VarReference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VarReferenceImpl extends WebElementVarReferenceImpl implements VarReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserPackage.Literals.VAR_REFERENCE;
  }

} //VarReferenceImpl
