/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.browser.ui.internal.BrowserActivator;

public class BrowserUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BrowserActivator.getInstance().getInjector("org.xtext.example.Browser");
	}

}
