/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalBrowserParser;
import org.xtext.example.mydsl.services.BrowserGrammarAccess;

public class BrowserParser extends AbstractAntlrParser {

	@Inject
	private BrowserGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBrowserParser createParser(XtextTokenStream stream) {
		return new InternalBrowserParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public BrowserGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BrowserGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
