/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.ide;

import org.xtext.example.ide.AbstractBrowserIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BrowserIdeModule extends AbstractBrowserIdeModule {
}
