/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.browser.BrowserFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browser";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Browser";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browser";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserPackage eINSTANCE = org.xtext.example.mydsl.browser.impl.BrowserPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ProgramImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__LINES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.LinesImpl <em>Lines</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.LinesImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getLines()
   * @generated
   */
  int LINES = 1;

  /**
   * The number of structural features of the '<em>Lines</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.FunctionCallImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 2;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = LINES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.DeclarationImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TYPE = LINES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__VAR = LINES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = LINES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.TypeImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getType()
   * @generated
   */
  int TYPE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.AffectationImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 5;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__REF = LINES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__EXPR = LINES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = LINES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.WebElementVarReferenceImpl <em>Web Element Var Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.WebElementVarReferenceImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getWebElementVarReference()
   * @generated
   */
  int WEB_ELEMENT_VAR_REFERENCE = 8;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_ELEMENT_VAR_REFERENCE__VAL = LINES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_ELEMENT_VAR_REFERENCE__NAME = LINES_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_ELEMENT_VAR_REFERENCE__PARAM = LINES_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Web Element Var Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_ELEMENT_VAR_REFERENCE_FEATURE_COUNT = LINES_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.VarReferenceImpl <em>Var Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.VarReferenceImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getVarReference()
   * @generated
   */
  int VAR_REFERENCE = 7;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REFERENCE__VAL = WEB_ELEMENT_VAR_REFERENCE__VAL;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REFERENCE__NAME = WEB_ELEMENT_VAR_REFERENCE__NAME;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REFERENCE__PARAM = WEB_ELEMENT_VAR_REFERENCE__PARAM;

  /**
   * The number of structural features of the '<em>Var Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REFERENCE_FEATURE_COUNT = WEB_ELEMENT_VAR_REFERENCE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.WebDriverVarReferenceImpl <em>Web Driver Var Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.WebDriverVarReferenceImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getWebDriverVarReference()
   * @generated
   */
  int WEB_DRIVER_VAR_REFERENCE = 9;

  /**
   * The number of structural features of the '<em>Web Driver Var Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_DRIVER_VAR_REFERENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.VariableImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.WebElementTypeImpl <em>Web Element Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.WebElementTypeImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getWebElementType()
   * @generated
   */
  int WEB_ELEMENT_TYPE = 11;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_ELEMENT_TYPE__CLASS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Web Element Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_ELEMENT_TYPE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.LinkImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getLink()
   * @generated
   */
  int LINK = 12;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NAME = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__URL = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.InputImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getInput()
   * @generated
   */
  int INPUT = 13;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NAME = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__VALUE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__TYPE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ButtonImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 14;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__VALUE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.TextImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getText()
   * @generated
   */
  int TEXT = 15;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NAME = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__VALUE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.CheckboxImpl <em>Checkbox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.CheckboxImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getCheckbox()
   * @generated
   */
  int CHECKBOX = 16;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__NAME = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__VALUE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Checkbox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ComboboxImpl <em>Combobox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ComboboxImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getCombobox()
   * @generated
   */
  int COMBOBOX = 17;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__NAME = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__VALUE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Combobox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ImageImpl <em>Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ImageImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getImage()
   * @generated
   */
  int IMAGE = 18;

  /**
   * The feature id for the '<em><b>Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__CLASS = WEB_ELEMENT_TYPE__CLASS;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__VALUE = WEB_ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = WEB_ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.GoImpl <em>Go</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.GoImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getGo()
   * @generated
   */
  int GO = 19;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO__VAL = FUNCTION_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO__URL = FUNCTION_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Go</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_FEATURE_COUNT = FUNCTION_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ContainsImpl <em>Contains</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ContainsImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getContains()
   * @generated
   */
  int CONTAINS = 20;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINS__VAL = FUNCTION_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINS__PARAM = FUNCTION_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Contains</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINS_FEATURE_COUNT = FUNCTION_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.InterractionsImpl <em>Interractions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.InterractionsImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getInterractions()
   * @generated
   */
  int INTERRACTIONS = 21;

  /**
   * The number of structural features of the '<em>Interractions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERRACTIONS_FEATURE_COUNT = FUNCTION_CALL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ClickImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getClick()
   * @generated
   */
  int CLICK = 22;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__VAL = INTERRACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = INTERRACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.FindPropertyImpl <em>Find Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.FindPropertyImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getFindProperty()
   * @generated
   */
  int FIND_PROPERTY = 23;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_PROPERTY__VAL = LINES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_PROPERTY__NAME = LINES_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_PROPERTY__PARAM = LINES_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Find Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_PROPERTY_FEATURE_COUNT = LINES_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.STRINGImpl <em>STRING</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.STRINGImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getSTRING()
   * @generated
   */
  int STRING = 24;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING__VAL = LINES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>STRING</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FEATURE_COUNT = LINES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.InsertImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 25;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__VAL = INTERRACTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__NAME = INTERRACTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = INTERRACTIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.CheckCheckboxImpl <em>Check Checkbox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.CheckCheckboxImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getCheckCheckbox()
   * @generated
   */
  int CHECK_CHECKBOX = 26;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_CHECKBOX__VAL = INTERRACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Check Checkbox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_CHECKBOX_FEATURE_COUNT = INTERRACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.ClearCheckboxImpl <em>Clear Checkbox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.ClearCheckboxImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getClearCheckbox()
   * @generated
   */
  int CLEAR_CHECKBOX = 27;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAR_CHECKBOX__VAL = INTERRACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Clear Checkbox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAR_CHECKBOX_FEATURE_COUNT = INTERRACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browser.impl.SelectComboboxImpl <em>Select Combobox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browser.impl.SelectComboboxImpl
   * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getSelectCombobox()
   * @generated
   */
  int SELECT_COMBOBOX = 28;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMBOBOX__VAL = INTERRACTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMBOBOX__PARAM = INTERRACTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select Combobox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMBOBOX_FEATURE_COUNT = INTERRACTIONS_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.browser.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.browser.Program#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see org.xtext.example.mydsl.browser.Program#getLines()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Lines();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Lines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lines</em>'.
   * @see org.xtext.example.mydsl.browser.Lines
   * @generated
   */
  EClass getLines();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see org.xtext.example.mydsl.browser.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.example.mydsl.browser.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Declaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.browser.Declaration#getType()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Declaration#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.example.mydsl.browser.Declaration#getVar()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mydsl.browser.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Type#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.browser.Type#getType()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see org.xtext.example.mydsl.browser.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Affectation#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.xtext.example.mydsl.browser.Affectation#getRef()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Ref();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Affectation#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.mydsl.browser.Affectation#getExpr()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Expr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.browser.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.VarReference <em>Var Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Reference</em>'.
   * @see org.xtext.example.mydsl.browser.VarReference
   * @generated
   */
  EClass getVarReference();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.WebElementVarReference <em>Web Element Var Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Web Element Var Reference</em>'.
   * @see org.xtext.example.mydsl.browser.WebElementVarReference
   * @generated
   */
  EClass getWebElementVarReference();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.WebElementVarReference#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.WebElementVarReference#getVal()
   * @see #getWebElementVarReference()
   * @generated
   */
  EReference getWebElementVarReference_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.WebElementVarReference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.WebElementVarReference#getName()
   * @see #getWebElementVarReference()
   * @generated
   */
  EAttribute getWebElementVarReference_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.WebElementVarReference#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.xtext.example.mydsl.browser.WebElementVarReference#getParam()
   * @see #getWebElementVarReference()
   * @generated
   */
  EAttribute getWebElementVarReference_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.WebDriverVarReference <em>Web Driver Var Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Web Driver Var Reference</em>'.
   * @see org.xtext.example.mydsl.browser.WebDriverVarReference
   * @generated
   */
  EClass getWebDriverVarReference();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.browser.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.WebElementType <em>Web Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Web Element Type</em>'.
   * @see org.xtext.example.mydsl.browser.WebElementType
   * @generated
   */
  EClass getWebElementType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.WebElementType#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Class</em>'.
   * @see org.xtext.example.mydsl.browser.WebElementType#getClass_()
   * @see #getWebElementType()
   * @generated
   */
  EAttribute getWebElementType_Class();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.example.mydsl.browser.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Link#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Link#getName()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Link#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.browser.Link#getUrl()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.xtext.example.mydsl.browser.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Input#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Input#getName()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Input#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.browser.Input#getValue()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Value();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Input#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.browser.Input#getType()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.example.mydsl.browser.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Button#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Button#getName()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Button#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.browser.Button#getValue()
   * @see #getButton()
   * @generated
   */
  EReference getButton_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.example.mydsl.browser.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Text#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Text#getName()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Text#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.browser.Text#getValue()
   * @see #getText()
   * @generated
   */
  EReference getText_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Checkbox <em>Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox</em>'.
   * @see org.xtext.example.mydsl.browser.Checkbox
   * @generated
   */
  EClass getCheckbox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Checkbox#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Checkbox#getName()
   * @see #getCheckbox()
   * @generated
   */
  EAttribute getCheckbox_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Checkbox#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.browser.Checkbox#getValue()
   * @see #getCheckbox()
   * @generated
   */
  EAttribute getCheckbox_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Combobox <em>Combobox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Combobox</em>'.
   * @see org.xtext.example.mydsl.browser.Combobox
   * @generated
   */
  EClass getCombobox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Combobox#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Combobox#getName()
   * @see #getCombobox()
   * @generated
   */
  EAttribute getCombobox_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Combobox#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.browser.Combobox#getValue()
   * @see #getCombobox()
   * @generated
   */
  EAttribute getCombobox_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Image <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image</em>'.
   * @see org.xtext.example.mydsl.browser.Image
   * @generated
   */
  EClass getImage();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Image#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.browser.Image#getValue()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Go <em>Go</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go</em>'.
   * @see org.xtext.example.mydsl.browser.Go
   * @generated
   */
  EClass getGo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Go#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.Go#getVal()
   * @see #getGo()
   * @generated
   */
  EReference getGo_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Go#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.browser.Go#getUrl()
   * @see #getGo()
   * @generated
   */
  EAttribute getGo_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Contains <em>Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contains</em>'.
   * @see org.xtext.example.mydsl.browser.Contains
   * @generated
   */
  EClass getContains();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Contains#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.Contains#getVal()
   * @see #getContains()
   * @generated
   */
  EReference getContains_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Contains#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.xtext.example.mydsl.browser.Contains#getParam()
   * @see #getContains()
   * @generated
   */
  EAttribute getContains_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Interractions <em>Interractions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interractions</em>'.
   * @see org.xtext.example.mydsl.browser.Interractions
   * @generated
   */
  EClass getInterractions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.example.mydsl.browser.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Click#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.Click#getVal()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.FindProperty <em>Find Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Find Property</em>'.
   * @see org.xtext.example.mydsl.browser.FindProperty
   * @generated
   */
  EClass getFindProperty();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.FindProperty#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.FindProperty#getVal()
   * @see #getFindProperty()
   * @generated
   */
  EReference getFindProperty_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.FindProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.FindProperty#getName()
   * @see #getFindProperty()
   * @generated
   */
  EAttribute getFindProperty_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.FindProperty#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.xtext.example.mydsl.browser.FindProperty#getParam()
   * @see #getFindProperty()
   * @generated
   */
  EAttribute getFindProperty_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.STRING <em>STRING</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STRING</em>'.
   * @see org.xtext.example.mydsl.browser.STRING
   * @generated
   */
  EClass getSTRING();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.STRING#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.STRING#getVal()
   * @see #getSTRING()
   * @generated
   */
  EReference getSTRING_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.example.mydsl.browser.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.Insert#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.Insert#getVal()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.Insert#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browser.Insert#getName()
   * @see #getInsert()
   * @generated
   */
  EAttribute getInsert_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.CheckCheckbox <em>Check Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check Checkbox</em>'.
   * @see org.xtext.example.mydsl.browser.CheckCheckbox
   * @generated
   */
  EClass getCheckCheckbox();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.CheckCheckbox#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.CheckCheckbox#getVal()
   * @see #getCheckCheckbox()
   * @generated
   */
  EReference getCheckCheckbox_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.ClearCheckbox <em>Clear Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clear Checkbox</em>'.
   * @see org.xtext.example.mydsl.browser.ClearCheckbox
   * @generated
   */
  EClass getClearCheckbox();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.ClearCheckbox#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.ClearCheckbox#getVal()
   * @see #getClearCheckbox()
   * @generated
   */
  EReference getClearCheckbox_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browser.SelectCombobox <em>Select Combobox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Combobox</em>'.
   * @see org.xtext.example.mydsl.browser.SelectCombobox
   * @generated
   */
  EClass getSelectCombobox();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browser.SelectCombobox#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.example.mydsl.browser.SelectCombobox#getVal()
   * @see #getSelectCombobox()
   * @generated
   */
  EReference getSelectCombobox_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browser.SelectCombobox#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.xtext.example.mydsl.browser.SelectCombobox#getParam()
   * @see #getSelectCombobox()
   * @generated
   */
  EAttribute getSelectCombobox_Param();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserFactory getBrowserFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ProgramImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__LINES = eINSTANCE.getProgram_Lines();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.LinesImpl <em>Lines</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.LinesImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getLines()
     * @generated
     */
    EClass LINES = eINSTANCE.getLines();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.FunctionCallImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.DeclarationImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__TYPE = eINSTANCE.getDeclaration_Type();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__VAR = eINSTANCE.getDeclaration_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.TypeImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__TYPE = eINSTANCE.getType_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.AffectationImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__REF = eINSTANCE.getAffectation_Ref();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__EXPR = eINSTANCE.getAffectation_Expr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.VarReferenceImpl <em>Var Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.VarReferenceImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getVarReference()
     * @generated
     */
    EClass VAR_REFERENCE = eINSTANCE.getVarReference();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.WebElementVarReferenceImpl <em>Web Element Var Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.WebElementVarReferenceImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getWebElementVarReference()
     * @generated
     */
    EClass WEB_ELEMENT_VAR_REFERENCE = eINSTANCE.getWebElementVarReference();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WEB_ELEMENT_VAR_REFERENCE__VAL = eINSTANCE.getWebElementVarReference_Val();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEB_ELEMENT_VAR_REFERENCE__NAME = eINSTANCE.getWebElementVarReference_Name();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEB_ELEMENT_VAR_REFERENCE__PARAM = eINSTANCE.getWebElementVarReference_Param();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.WebDriverVarReferenceImpl <em>Web Driver Var Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.WebDriverVarReferenceImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getWebDriverVarReference()
     * @generated
     */
    EClass WEB_DRIVER_VAR_REFERENCE = eINSTANCE.getWebDriverVarReference();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.VariableImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.WebElementTypeImpl <em>Web Element Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.WebElementTypeImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getWebElementType()
     * @generated
     */
    EClass WEB_ELEMENT_TYPE = eINSTANCE.getWebElementType();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEB_ELEMENT_TYPE__CLASS = eINSTANCE.getWebElementType_Class();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.LinkImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__NAME = eINSTANCE.getLink_Name();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__URL = eINSTANCE.getLink_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.InputImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__NAME = eINSTANCE.getInput_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__VALUE = eINSTANCE.getInput_Value();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__TYPE = eINSTANCE.getInput_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ButtonImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__NAME = eINSTANCE.getButton_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__VALUE = eINSTANCE.getButton_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.TextImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__NAME = eINSTANCE.getText_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT__VALUE = eINSTANCE.getText_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.CheckboxImpl <em>Checkbox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.CheckboxImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getCheckbox()
     * @generated
     */
    EClass CHECKBOX = eINSTANCE.getCheckbox();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__NAME = eINSTANCE.getCheckbox_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX__VALUE = eINSTANCE.getCheckbox_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ComboboxImpl <em>Combobox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ComboboxImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getCombobox()
     * @generated
     */
    EClass COMBOBOX = eINSTANCE.getCombobox();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__NAME = eINSTANCE.getCombobox_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__VALUE = eINSTANCE.getCombobox_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ImageImpl <em>Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ImageImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getImage()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getImage();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__VALUE = eINSTANCE.getImage_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.GoImpl <em>Go</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.GoImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getGo()
     * @generated
     */
    EClass GO = eINSTANCE.getGo();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GO__VAL = eINSTANCE.getGo_Val();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO__URL = eINSTANCE.getGo_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ContainsImpl <em>Contains</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ContainsImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getContains()
     * @generated
     */
    EClass CONTAINS = eINSTANCE.getContains();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINS__VAL = eINSTANCE.getContains_Val();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINS__PARAM = eINSTANCE.getContains_Param();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.InterractionsImpl <em>Interractions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.InterractionsImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getInterractions()
     * @generated
     */
    EClass INTERRACTIONS = eINSTANCE.getInterractions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ClickImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__VAL = eINSTANCE.getClick_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.FindPropertyImpl <em>Find Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.FindPropertyImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getFindProperty()
     * @generated
     */
    EClass FIND_PROPERTY = eINSTANCE.getFindProperty();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIND_PROPERTY__VAL = eINSTANCE.getFindProperty_Val();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIND_PROPERTY__NAME = eINSTANCE.getFindProperty_Name();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIND_PROPERTY__PARAM = eINSTANCE.getFindProperty_Param();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.STRINGImpl <em>STRING</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.STRINGImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getSTRING()
     * @generated
     */
    EClass STRING = eINSTANCE.getSTRING();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRING__VAL = eINSTANCE.getSTRING_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.InsertImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__VAL = eINSTANCE.getInsert_Val();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT__NAME = eINSTANCE.getInsert_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.CheckCheckboxImpl <em>Check Checkbox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.CheckCheckboxImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getCheckCheckbox()
     * @generated
     */
    EClass CHECK_CHECKBOX = eINSTANCE.getCheckCheckbox();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK_CHECKBOX__VAL = eINSTANCE.getCheckCheckbox_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.ClearCheckboxImpl <em>Clear Checkbox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.ClearCheckboxImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getClearCheckbox()
     * @generated
     */
    EClass CLEAR_CHECKBOX = eINSTANCE.getClearCheckbox();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLEAR_CHECKBOX__VAL = eINSTANCE.getClearCheckbox_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browser.impl.SelectComboboxImpl <em>Select Combobox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browser.impl.SelectComboboxImpl
     * @see org.xtext.example.mydsl.browser.impl.BrowserPackageImpl#getSelectCombobox()
     * @generated
     */
    EClass SELECT_COMBOBOX = eINSTANCE.getSelectCombobox();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_COMBOBOX__VAL = eINSTANCE.getSelectCombobox_Val();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_COMBOBOX__PARAM = eINSTANCE.getSelectCombobox_Param();

  }

} //BrowserPackage
