/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check Checkbox</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browser.CheckCheckbox#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browser.BrowserPackage#getCheckCheckbox()
 * @model
 * @generated
 */
public interface CheckCheckbox extends Interractions
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(WebElementVarReference)
   * @see org.xtext.example.mydsl.browser.BrowserPackage#getCheckCheckbox_Val()
   * @model containment="true"
   * @generated
   */
  WebElementVarReference getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browser.CheckCheckbox#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(WebElementVarReference value);

} // CheckCheckbox
