/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clear Checkbox</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browser.ClearCheckbox#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browser.BrowserPackage#getClearCheckbox()
 * @model
 * @generated
 */
public interface ClearCheckbox extends Interractions
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(WebDriverVarReference)
   * @see org.xtext.example.mydsl.browser.BrowserPackage#getClearCheckbox_Val()
   * @model containment="true"
   * @generated
   */
  WebDriverVarReference getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browser.ClearCheckbox#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(WebDriverVarReference value);

} // ClearCheckbox
