/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contains</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browser.Contains#getVal <em>Val</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browser.Contains#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browser.BrowserPackage#getContains()
 * @model
 * @generated
 */
public interface Contains extends FunctionCall
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(WebElementVarReference)
   * @see org.xtext.example.mydsl.browser.BrowserPackage#getContains_Val()
   * @model containment="true"
   * @generated
   */
  WebElementVarReference getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browser.Contains#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(WebElementVarReference value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' attribute.
   * @see #setParam(String)
   * @see org.xtext.example.mydsl.browser.BrowserPackage#getContains_Param()
   * @model
   * @generated
   */
  String getParam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browser.Contains#getParam <em>Param</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' attribute.
   * @see #getParam()
   * @generated
   */
  void setParam(String value);

} // Contains
