/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.browser.BrowserPackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends Lines
{
} // FunctionCall
