/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lines</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.browser.BrowserPackage#getLines()
 * @model
 * @generated
 */
public interface Lines extends EObject
{
} // Lines
